### PR TITLE
Adding support for tcp_nodelay.

### PR DESCRIPTION
**Pull request by nmdguerreiro**

### CODE REVIEW

**Comment by kellabyte** [comment]
Interesting! Did you benchmark this at all? I'm curious how this affects performance :) Sorry I was so slow at responding!

**Comment by kellabyte** [comment]
If I don't specify `--tcp_nodelay` it still enables it. I think you need to provide a default value of false somewhere.

I did a quick benchmark:

# Nagle

### Keep-alive
```
../bin/wrk/wrk --latency -d 10s -t 8 -c 128 http://192.168.0.101:8000
Running 10s test @ http://192.168.0.101:8000
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.03ms    1.79ms  53.26ms   92.50%
    Req/Sec    22.28k    12.93k   57.35k    67.25%
  Latency Distribution
     50%  514.00us
     75%    0.99ms
     90%    2.30ms
     99%    8.58ms
  1774843 requests in 10.10s, 267.43MB read
Requests/sec: 175781.87
Transfer/sec:     26.49MB
```

### Pipelined
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.16ms    4.59ms  53.00ms   70.80%
    Req/Sec   107.87k    22.01k  188.43k    69.62%
  Latency Distribution
     50%    2.03ms
     75%   40.34ms
     90%    0.00us
     99%    0.00us
  8598798 requests in 10.02s, 1.27GB read
Requests/sec: 857775.85
Transfer/sec:    129.25MB
```

# NODELAY

### Keep-alive
```
../bin/wrk/wrk --latency -d 10s -t 8 -c 128 http://192.168.0.101:8000
Running 10s test @ http://192.168.0.101:8000
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.91ms    1.36ms  47.34ms   92.20%
    Req/Sec    22.65k    13.35k   54.51k    59.18%
  Latency Distribution
     50%  513.00us
     75%    0.95ms
     90%    1.89ms
     99%    6.97ms
  1806006 requests in 10.10s, 271.96MB read
Requests/sec: 178829.83
Transfer/sec:     26.93MB
```

### Pipelined
```
./bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.87ms   12.23ms 122.71ms   79.19%
    Req/Sec    37.17k    27.15k  138.23k    72.32%
  Latency Distribution
     50%    6.03ms
     75%   18.15ms
     90%   43.36ms
     99%    0.00us
  2974326 requests in 10.10s, 448.17MB read
Requests/sec: 294454.95
Transfer/sec:     44.37MB
```

Looks like it hurts pipelined requests but pipelined requests aren't a very common real world workload. I would still like to add this PR to Haywire. Can you fix the default of off and I'll merge :)

**Comment by nmdguerreiro** [comment]
@kellabyte Thanks for the feedback. I had made a switch to use a bool value to store the config value in most of the code, but I had forgotten `haywire.h`. 

Here's an strace confirming that it works properly now:

## Default behaviour
```
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 74
setsockopt(74, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(74, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
write(1, "Address: 0.0.0.0\n", 17Address: 0.0.0.0
)      = 17
write(1, "Port: 8000\n", 11Port: 8000
)            = 11
write(1, "Threads: 16\n", 12Threads: 16
)           = 12
write(1, "Parser: http_parser\n", 20Parser: http_parser
)   = 20
write(1, "TCP No Delay: off\n", 18TCP No Delay: off
)     = 18
write(1, "Listening...\n", 13Listening...
)          = 13
```

# Nodelay

```
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 74
setsockopt(74, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(74, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(74, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
write(1, "Address: 0.0.0.0\n", 17Address: 0.0.0.0
)      = 17
write(1, "Port: 8000\n", 11Port: 8000
)            = 11
write(1, "Threads: 16\n", 12Threads: 16
)           = 12
write(1, "Parser: http_parser\n", 20Parser: http_parser
)   = 20
write(1, "TCP No Delay: on\n", 17TCP No Delay: on
)      = 17
write(1, "Listening...\n", 13Listening...
)          = 13
```

As for performance, I think you'd only see an impact with response bodies spanning multiple TCP packets. I tried to replicate that scenario, but I'm getting hit by #54 :cry:

**Comment by nmdguerreiro** [comment]
Opened #70 to fix #54.

**Comment by kellabyte** [comment]
Okay so it seems like this default option is now working. I'm going to merge the PR :)

Here are the results I observed benchmarking.

### TCP_NODELAY OFF
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.15ms    4.70ms  53.92ms   71.03%
    Req/Sec   107.84k    26.23k  190.06k    73.88%
  Latency Distribution
     50%    1.96ms
     75%   38.56ms
     90%    0.00us
     99%    0.00us
  8595746 requests in 10.02s, 1.26GB read
Requests/sec: 858070.66
Transfer/sec:    129.29MB
```

### TCP_NODELAY ON
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.11ms   12.70ms 124.75ms   73.51%
    Req/Sec    59.91k    42.31k  183.23k    66.58%
  Latency Distribution
     50%    6.27ms
     75%   23.68ms
     90%    0.00us
     99%    0.00us
  4774785 requests in 10.07s, 719.47MB read
Requests/sec: 474182.83
Transfer/sec:     71.45MB
```

Now keep in mind latency distribution in `Wrk` is incorrect because it doesn't deal with coordinated omission so we use `Wrk2` to get valid latency distribution results.

### TCP_NODELAY OFF Pipelined
```
../bin/wrk2/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 -R 300000 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.66ms    5.65ms  82.30ms   94.70%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.43ms
 75.000%    1.85ms
 90.000%    2.39ms
 99.000%   33.22ms
 99.900%   52.48ms
 99.990%   67.65ms
 99.999%   76.16ms
100.000%   82.37ms
```

### TCP_NODELAY ON Pipelined
```
./bin/wrk2/wrk --script ./pipelined_get.lua --latency -d 10s -t 8 -c 32 -R 300000 http://192.168.0.101:8000 -- 64
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   698.91ms    1.20s    5.86s    84.97%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   23.60ms
 75.000%    1.01s
 90.000%    2.40s
 99.000%    5.33s
 99.900%    5.76s
 99.990%    5.83s
 99.999%    5.86s
100.000%    5.87s
```

### TCP_NODELAY OFF Non-pipelined
```
../bin/wrk2/wrk --latency -d 10s -t 8 -c 32 -R 50000 http://192.168.0.101:8000
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.17ms  583.79us   5.10ms   65.13%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.13ms
 75.000%    1.56ms
 90.000%    1.97ms
 99.000%    2.65ms
 99.900%    3.20ms
 99.990%    3.87ms
 99.999%    4.74ms
100.000%    5.10ms
```

### TCP_NODELAY ON Non-pipelined
```
../bin/wrk2/wrk --latency -d 10s -t 8 -c 32 -R 50000 http://192.168.0.101:8000
Running 10s test @ http://192.168.0.101:8000
  8 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.15ms  550.76us   4.63ms   64.11%
    Req/Sec       -nan      -nan   0.00      0.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.13ms
 75.000%    1.54ms
 90.000%    1.89ms
 99.000%    2.44ms
 99.900%    2.94ms
 99.990%    3.51ms
 99.999%    4.24ms
100.000%    4.64ms
```

**Comment by nmdguerreiro** [comment]
Awesome! Thanks :smile:

**Comment by kellabyte** [comment]
No thank you! :)

**Pull request merged**
